#include <stdint.h>  
#include <pic32mx.h> 
#include "Projectheader.h"

/*
Written 2020 by Frida Johansson and David Strömqvist
*/

int scoreboard [3];
char nameboard [3][3];
/*
Function highscore todo
puts the highscore in an array
int scoreboard [3] = 0;
*/

void highscore (int scores, char *name){
	int tempscore = scores;
	char tempname[3];
	int i,j;
    for(i = 0; i < 3; i++){
        if (scoreboard[i] < scores) {
            tempscore = scoreboard[i];
            scoreboard[i] = scores;
            scores = tempscore;
			for(j = 0; j < 3; j++){
				tempname[j] = nameboard[i][j];
				nameboard[i][j] = *name;
				*name = tempname[j];
				name++;
			}
			name -= 3;
        }
	}
	WriteToMem();
}

/*
	Checks if the new score is a high score.
*/
int8_t newHighScore(int score)
{
	int i;
	for (i = 0; i < 3; i++)
	{
		if (score > scoreboard[i])
			return 1;
	}
	return 0;
}
/*
game over
kolla om poäng är högre än listan
om högre. -> gå till skärm "enter name"
returnerar textsträng, 3 tecken lång. 
kör itoaconv, sätt ihop namnet och mellanrum plus sträng från itoaconv 
*/


/* Wait for I2C bus to become idle */
void i2c_idle() {
	while(I2C1CON & 0x1F || I2C1STAT & (1 << 14)); //TRSTAT
}

/* Send one byte on I2C bus, return ack/nack status of transaction */
int8_t i2c_send(uint8_t data) {
	i2c_idle();
	I2C1TRN = data;
	i2c_idle();
	return !(I2C1STAT & (1 << 15)); //ACKSTAT
}

/* Receive one byte from I2C bus */
uint8_t i2c_recv() {
	i2c_idle();
	I2C1CONSET = 1 << 3; //RCEN = 1
	i2c_idle();
	I2C1STATCLR = 1 << 6; //I2COV = 0
	return I2C1RCV;
}

/* Send acknowledge conditon on the bus */
void i2c_ack() {
	i2c_idle();
	I2C1CONCLR = 1 << 5; //ACKDT = 0
	I2C1CONSET = 1 << 4; //ACKEN = 1
}

/* Send not-acknowledge conditon on the bus */
void i2c_nack() {
	i2c_idle();
	I2C1CONSET = 1 << 5; //ACKDT = 1
	I2C1CONSET = 1 << 4; //ACKEN = 1
}

/* Send start conditon on the bus */
void i2c_start() {
	i2c_idle();
	I2C1CONSET = 1 << 0; //SEN
	i2c_idle();
}

/* Send restart conditon on the bus */
void i2c_restart() {
	i2c_idle();
	I2C1CONSET = 1 << 1; //RSEN
	i2c_idle();
}

/* Send stop conditon on the bus */
void i2c_stop() {

	i2c_idle();
	I2C1CONSET = 1 << 2; //PEN
	i2c_idle();
}
void meminit(){
	uint16_t temp;
	/* Set up i2c */
	I2C1CON = 0x0;
	/* I2C Baud rate should be less than 400 kHz, is generated by dividing
	the 40 MHz peripheral bus clock down */
	I2C1BRG = 0x0fa;
	I2C1STAT = 0x0;
	I2C1CONSET = 1 << 13; 					//SIDL = 1
	I2C1CONSET = 1 << 15; 					// ON = 1
	temp = I2C1RCV; 	 				//Clear receive buffer
}	
	
void WriteToMem(){
	i2c_start();
	while(!i2c_send(MEM_ADDRESS << 1 | 0));
	int i,j;
	i2c_send(0);
	i2c_send(0);
	for(i = 0; i < 3; i++){
		int temp = scoreboard[i];
		for(j = 0; j < 3; j++){
			i2c_send((uint8_t)nameboard[i][j]);
			
		}
		for(j = 0; j < 4; j++){
			i2c_send((uint8_t)(temp & 0xff));
			temp = temp >> 8;
		}
		
	}
	i2c_stop();
	
}

uint8_t ReadToMem(){
	int i,j;
	uint32_t recieved [4]; 
	i2c_start();
	while( (!i2c_send( (MEM_ADDRESS << 1) | 0)) ){}
	i2c_send(0);
	i2c_send(0);
	i2c_restart();
	while( (!i2c_send( (MEM_ADDRESS << 1) | 1)) ){}
	for(i = 0; i < 3; i++){
		uint32_t temp = 0;
		for(j = 0; j < 3; j++){
			nameboard[i][j] = i2c_recv();
			i2c_ack();
			
		}
		for(j = 0; j < 4; j++){
			recieved[j] = i2c_recv();
			if(i == 2 && j == 3)
				i2c_nack();
			else
				i2c_ack();
			
		}
		temp = ( (recieved[3] << 24) | (recieved[2] << 16) | (recieved[1] << 8) | (recieved[0]) );
		scoreboard[i] = (int)temp;
	}
	
	i2c_stop();
}